name: Lint check commit
on:
  push:
    branches:
      - main

jobs:
  lint-check:
    runs-on: ubuntu-latest
    environment: lint-checker
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1
        
      - name: Lint checking
        uses: ricardochaves/python-lint@32032eca67291cd71f88d79e61bc4b904ee03265
        with:
          python-root-list: '**/*.py'
          use-flake8: true
          use-pylint: false
          use-pycodestyle: false
          use-black: false
          use-mypy: false
          use-isort: false
